name: expense
version: '3.8'
networks :
  default:
    name:expense
services:
  mysql:
    image: mysql:v1.0.0
    container_name: mysql  # equal to --name mysql
  backend: 
      image: backen:v1.0.0
      container_name: backend
      depends_on: mysql
  frontend:
    image: frontend:v1.0.0
    container_name: frontend
    depens_on: 
    - backend
    ports:
    - "80:80"




